import React from 'react';
import { AlertTriangle } from 'lucide-react';
import '../../styles/viewUTurnAlert.css';

const UTurnNotificationMessageCard = ({ alert }) => {
  const notificationTitle = alert?.notificationTitle || 'Unsafe U-Turn Detected';
  const priority = alert?.priority || 'High';

  return (
    <div className="uturn-notification-card">
      <h4 className="uturn-card-title">Notification Message</h4>

      <div className="uturn-warning-box">
        <div className="uturn-warning-icon-wrapper">
          <AlertTriangle size={28} />
        </div>

        <h3 className="uturn-warning-title">{notificationTitle}</h3>

        <p className="uturn-warning-desc">
          A <strong>{priority}-priority</strong> U-Turn alert has been automatically triggered by
          the roadside sensor system. A bus or vehicle in the monitored zone has performed or
          attempted an illegal U-Turn maneuver that violates traffic regulations and poses a
          significant safety risk to other road users.
        </p>

        <p className="uturn-warning-action-note">
          ⚠ Immediate action is required by traffic enforcement officers. Deploy patrol units
          to the flagged location and verify the incident. Failure to respond within the defined
          SLA may escalate this alert to the supervising officer.
        </p>

        <p className="uturn-warning-footer-note">
          This is an automated alert generated by the SLTB SafeTrack AI roadside monitoring
          system. Do not reply to this notification directly.
        </p>
      </div>
    </div>
  );
};

export default UTurnNotificationMessageCard;
