import React from 'react';
import { AlertTriangle, Info } from 'lucide-react';
import '../../styles/viewUTurnAlert.css';

const UTurnNotificationMessageCard = ({ alert }) => {
  const notificationTitle = alert?.notificationTitle ?? alert?.notification_title ?? 'Unsafe U-Turn Detected';
  const priority = alert?.priority ?? 'Medium';
  const message = alert?.message || alert?.notification?.message || '';

  return (
    <div className="uturn-notification-card">
      <h4 className="uturn-card-title">Notification Message</h4>

      <div className="uturn-warning-box">
        <div className="uturn-warning-icon-wrapper">
          <AlertTriangle size={28} />
        </div>

        <h3 className="uturn-warning-title">{notificationTitle}</h3>

        {message ? (
          <p className="uturn-warning-desc" style={{ fontSize: '0.9rem', color: '#1e293b', fontWeight: 500 }}>
            {message}
          </p>
        ) : (
          <p className="uturn-warning-desc">
            A <strong>{priority}-priority</strong> U-Turn alert was logged by the roadside sensor system.
            A vehicle in the monitored sector triggered a roadside proximity violation.
          </p>
        )}

        <div style={{ background: '#f8fafc', borderRadius: '8px', padding: '0.85rem', marginTop: '1rem', border: '1px solid #e2e8f0' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: '#475569', fontWeight: 700, fontSize: '0.78rem', marginBottom: '0.35rem' }}>
            <Info size={14} color="#0047ff" />
            <span>Enforcement Protocol</span>
          </div>
          <p className="uturn-warning-action-note" style={{ margin: 0 }}>
            Verify the alert timestamp and location against roadside camera records. In the event of a dangerous obstruction, dispatch nearest patrol unit.
          </p>
        </div>

        <p className="uturn-warning-footer-note" style={{ marginTop: '1.25rem' }}>
          Automated alert generated by SLTB SafeTrack AI roadside monitoring unit. Record synchronized via MySQL.
        </p>
      </div>
    </div>
  );
};

export default UTurnNotificationMessageCard;
