import React from 'react';
import { ArrowLeft, Save, Calendar } from 'lucide-react';
import '../../../styles/addUser.css';

const PoliceAdminStep = ({
  formData,
  errors,
  onChange,
  onBack,
  onSave,
}) => {
  return (
    <div className="add-user-card">
      {/* Header */}
      <div className="add-user-step-header">
        <span className="add-user-step-badge">2</span>
        <h2 className="add-user-step-title">Police Officer Information</h2>
      </div>

      {/* Grid Fields */}
      <div className="add-user-form-grid">
        {/* Officer ID */}
        <div className="add-user-field-group">
          <label className="add-user-label">Officer ID</label>
          <input
            type="text"
            className="add-user-input readonly"
            value="Auto generated"
            readOnly
          />
          <span className="add-user-helper-text">
            Officer ID is generated by the system
          </span>
        </div>

        {/* User ID */}
        <div className="add-user-field-group">
          <label className="add-user-label">User ID</label>
          <input
            type="text"
            className="add-user-input readonly"
            value="Linked from previous step"
            readOnly
          />
          <span className="add-user-helper-text">
            User ID is linked from Step 1
          </span>
        </div>

        {/* Full Name */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Full Name <span className="req">*</span>
          </label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter full name"
            value={formData.fullName || ''}
            onChange={(e) => onChange('fullName', e.target.value)}
          />
          {errors.fullName ? (
            <span className="add-user-error-text">{errors.fullName}</span>
          ) : null}
        </div>

        {/* Badge Number */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Badge Number <span className="req">*</span>
          </label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter badge number"
            value={formData.badgeNumber || ''}
            onChange={(e) => onChange('badgeNumber', e.target.value)}
          />
          {errors.badgeNumber ? (
            <span className="add-user-error-text">{errors.badgeNumber}</span>
          ) : null}
        </div>

        {/* Rank */}
        <div className="add-user-field-group">
          <label className="add-user-label">Rank</label>
          <select
            className="add-user-select"
            value={formData.rank || ''}
            onChange={(e) => onChange('rank', e.target.value)}
          >
            <option value="">Select rank</option>
            <option value="Inspector">Inspector</option>
            <option value="Chief Inspector">Chief Inspector</option>
            <option value="Sergeant">Sergeant</option>
            <option value="Constable">Constable</option>
            <option value="Sub-Inspector">Sub-Inspector</option>
          </select>
        </div>

        {/* Police Station */}
        <div className="add-user-field-group">
          <label className="add-user-label">Police Station</label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter police station"
            value={formData.policeStation || ''}
            onChange={(e) => onChange('policeStation', e.target.value)}
          />
        </div>

        {/* Phone */}
        <div className="add-user-field-group">
          <label className="add-user-label">Phone</label>
          <input
            type="tel"
            className="add-user-input"
            placeholder="Enter phone number"
            value={formData.phone || ''}
            onChange={(e) => onChange('phone', e.target.value)}
          />
          <span className="add-user-helper-text">Enter valid contact number</span>
        </div>

        {/* Joined Date */}
        <div className="add-user-field-group">
          <label className="add-user-label">Joined Date</label>
          <div className="add-user-date-wrap">
            <input
              type="text"
              className="add-user-input"
              placeholder="Select joined date"
              value={formData.joinedDate || ''}
              onChange={(e) => onChange('joinedDate', e.target.value)}
            />
            <Calendar size={15} className="add-user-date-icon" />
          </div>
          <span className="add-user-helper-text">
            Select the date when officer joined
          </span>
        </div>

        {/* Device Token */}
        <div className="add-user-field-group">
          <label className="add-user-label">Device Token</label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter device token"
            value={formData.deviceToken || ''}
            onChange={(e) => onChange('deviceToken', e.target.value)}
          />
          <span className="add-user-helper-text">
            Token used for device identification and notifications
          </span>
        </div>

        {/* Is Online */}
        <div className="add-user-field-group">
          <label className="add-user-label">Is Online</label>
          <select
            className="add-user-select"
            value={formData.isOnline || ''}
            onChange={(e) => onChange('isOnline', e.target.value)}
          >
            <option value="">Select status</option>
            <option value="Online">Online</option>
            <option value="Offline">Offline</option>
          </select>
          <span className="add-user-helper-text">Select current online status</span>
        </div>

        {/* Last Active */}
        <div className="add-user-field-group">
          <label className="add-user-label">Last Active</label>
          <div className="add-user-date-wrap">
            <input
              type="text"
              className="add-user-input"
              placeholder="Select date and time"
              value={formData.lastActive || ''}
              onChange={(e) => onChange('lastActive', e.target.value)}
            />
            <Calendar size={15} className="add-user-date-icon" />
          </div>
          <span className="add-user-helper-text">
            Last time the officer was active in the system
          </span>
        </div>
      </div>

      {/* Footer Actions */}
      <div className="add-user-footer-actions">
        <button type="button" className="btn-wizard-back" onClick={onBack}>
          <ArrowLeft size={14} />
          Back
        </button>
        <button type="button" className="btn-wizard-save" onClick={onSave}>
          <Save size={15} />
          Save User
        </button>
      </div>
    </div>
  );
};

export default PoliceAdminStep;
