import React from 'react';
import { ArrowLeft, Save, Calendar } from 'lucide-react';
import '../../../styles/addUser.css';

const SLTBAdminStep = ({
  formData,
  errors,
  onChange,
  onBack,
  onSave,
}) => {
  return (
    <div className="add-user-card">
      {/* Header */}
      <div className="add-user-step-header">
        <span className="add-user-step-badge">2</span>
        <h2 className="add-user-step-title">SLTB User Information</h2>
      </div>

      {/* Grid Fields */}
      <div className="add-user-form-grid">
        {/* SLTB User ID */}
        <div className="add-user-field-group">
          <label className="add-user-label">SLTB User ID</label>
          <input
            type="text"
            className="add-user-input readonly"
            value="Auto generated"
            readOnly
          />
          <span className="add-user-helper-text">Generated by the system</span>
        </div>

        {/* User ID */}
        <div className="add-user-field-group">
          <label className="add-user-label">User ID</label>
          <input
            type="text"
            className="add-user-input readonly"
            value="Linked from Step 1"
            readOnly
          />
          <span className="add-user-helper-text">
            Linked from the user account created in Step 1
          </span>
        </div>

        {/* Full Name */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Full Name <span className="req">*</span>
          </label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter full name"
            value={formData.fullName || ''}
            onChange={(e) => onChange('fullName', e.target.value)}
          />
          {errors.fullName ? (
            <span className="add-user-error-text">{errors.fullName}</span>
          ) : null}
        </div>

        {/* Designation */}
        <div className="add-user-field-group">
          <label className="add-user-label">Designation</label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter designation"
            value={formData.designation || ''}
            onChange={(e) => onChange('designation', e.target.value)}
          />
        </div>

        {/* Employee ID */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Employee ID <span className="req">*</span>
          </label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter employee ID"
            value={formData.employeeId || ''}
            onChange={(e) => onChange('employeeId', e.target.value)}
          />
          {errors.employeeId ? (
            <span className="add-user-error-text">{errors.employeeId}</span>
          ) : (
            <span className="add-user-helper-text">
              Unique employee identifier
            </span>
          )}
        </div>

        {/* Phone */}
        <div className="add-user-field-group">
          <label className="add-user-label">Phone</label>
          <input
            type="tel"
            className="add-user-input"
            placeholder="Enter phone number"
            value={formData.phone || ''}
            onChange={(e) => onChange('phone', e.target.value)}
          />
        </div>

        {/* Department */}
        <div className="add-user-field-group">
          <label className="add-user-label">Department</label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter department"
            value={formData.department || ''}
            onChange={(e) => onChange('department', e.target.value)}
          />
        </div>

        {/* Joined Date */}
        <div className="add-user-field-group">
          <label className="add-user-label">Joined Date</label>
          <div className="add-user-date-wrap">
            <input
              type="text"
              className="add-user-input"
              placeholder="Select date"
              value={formData.joinedDate || ''}
              onChange={(e) => onChange('joinedDate', e.target.value)}
            />
            <Calendar size={15} className="add-user-date-icon" />
          </div>
          <span className="add-user-helper-text">Select joined date</span>
        </div>
      </div>

      {/* Footer Actions */}
      <div className="add-user-footer-actions">
        <button type="button" className="btn-wizard-back" onClick={onBack}>
          <ArrowLeft size={14} />
          Back
        </button>
        <button type="button" className="btn-wizard-save" onClick={onSave}>
          <Save size={15} />
          Save User
        </button>
      </div>
    </div>
  );
};

export default SLTBAdminStep;
