import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import PasswordField from './PasswordField';
import ImageUploader from './ImageUploader';
import '../../../styles/addUser.css';

const UserStepOne = ({
  formData,
  errors,
  onChange,
  onImageChange,
  onImageRemove,
  onNext,
}) => {
  return (
    <div className="add-user-card">
      {/* Header */}
      <div className="add-user-step-header">
        <span className="add-user-step-badge">1</span>
        <h2 className="add-user-step-title">User Information</h2>
      </div>

      {/* Grid Fields */}
      <div className="add-user-form-grid">
        {/* User ID */}
        <div className="add-user-field-group">
          <label className="add-user-label">User ID</label>
          <input
            type="text"
            className="add-user-input readonly"
            value="Auto generated"
            readOnly
          />
          <span className="add-user-helper-text">
            User ID is generated by the system
          </span>
        </div>

        {/* Role ID */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Role ID <span className="req">*</span>
          </label>
          <select
            className="add-user-select"
            value={formData.role}
            onChange={(e) => onChange('role', e.target.value)}
          >
            <option value="">Select role</option>
            <option value="Police Admin">Police Admin</option>
            <option value="SLTB Admin">SLTB Admin</option>
            <option value="Traffic Police Officer">Traffic Police Officer</option>
          </select>
          {errors.role ? (
            <span className="add-user-error-text">{errors.role}</span>
          ) : (
            <span className="add-user-helper-text">Select the user role</span>
          )}
        </div>

        {/* Username */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Username <span className="req">*</span>
          </label>
          <input
            type="text"
            className="add-user-input"
            placeholder="Enter username"
            value={formData.username}
            onChange={(e) => onChange('username', e.target.value)}
          />
          {errors.username ? (
            <span className="add-user-error-text">{errors.username}</span>
          ) : (
            <span className="add-user-helper-text">Enter unique username</span>
          )}
        </div>

        {/* Email */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Email <span className="req">*</span>
          </label>
          <input
            type="email"
            className="add-user-input"
            placeholder="Enter email address"
            value={formData.email}
            onChange={(e) => onChange('email', e.target.value)}
          />
          {errors.email ? (
            <span className="add-user-error-text">{errors.email}</span>
          ) : (
            <span className="add-user-helper-text">Enter valid email address</span>
          )}
        </div>

        {/* Password */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Password <span className="req">*</span>
          </label>
          <PasswordField
            value={formData.password}
            onChange={(e) => onChange('password', e.target.value)}
            placeholder="Enter password"
          />
          {errors.password ? (
            <span className="add-user-error-text">{errors.password}</span>
          ) : (
            <span className="add-user-helper-text">Enter a strong password</span>
          )}
        </div>

        {/* Profile Image */}
        <div className="add-user-field-group">
          <label className="add-user-label">Profile Image</label>
          <ImageUploader
            imagePreview={formData.imagePreview}
            onImageChange={onImageChange}
            onImageRemove={onImageRemove}
          />
          <span className="add-user-helper-text">Upload user profile image</span>
        </div>

        {/* Theme Preference */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Theme Preference <span className="req">*</span>
          </label>
          <select
            className="add-user-select"
            value={formData.themePreference}
            onChange={(e) => onChange('themePreference', e.target.value)}
          >
            <option value="Light">Light</option>
            <option value="Dark">Dark</option>
            <option value="System Default">System Default</option>
          </select>
          <span className="add-user-helper-text">Select theme preference</span>
        </div>

        {/* Status */}
        <div className="add-user-field-group">
          <label className="add-user-label">
            Status <span className="req">*</span>
          </label>
          <select
            className="add-user-select"
            value={formData.status}
            onChange={(e) => onChange('status', e.target.value)}
          >
            <option value="Active">Active</option>
            <option value="Inactive">Inactive</option>
          </select>
          <span className="add-user-helper-text">Select user status</span>
        </div>

        {/* Created At */}
        <div className="add-user-field-group">
          <label className="add-user-label">Created At</label>
          <input
            type="text"
            className="add-user-input readonly"
            value="Auto generated on save"
            readOnly
          />
          <span className="add-user-helper-text">
            Created timestamp is generated by the system
          </span>
        </div>

        {/* Updated At */}
        <div className="add-user-field-group">
          <label className="add-user-label">Updated At</label>
          <input
            type="text"
            className="add-user-input readonly"
            value="Auto generated on save"
            readOnly
          />
          <span className="add-user-helper-text">
            Updated timestamp is generated by the system
          </span>
        </div>
      </div>

      {/* Footer Actions */}
      <div className="add-user-footer-actions">
        <Link to="/police/user-management" className="btn-wizard-cancel">
          <ArrowLeft size={14} />
          Cancel
        </Link>
        <button type="button" className="btn-wizard-next" onClick={onNext}>
          Next
          <ArrowRight size={14} />
        </button>
      </div>
    </div>
  );
};

export default UserStepOne;
