import React from 'react';
import '../../../styles/addDevice.css';

/**
 * Reusable DeviceInformationForm — used by both AddDevicePage and EditDevicePage.
 * Props:
 *   formData, errors, onChange, isEdit (bool)
 */
const DeviceInformationForm = ({ formData, errors, onChange, isEdit }) => {
  const handleChange = (field) => (e) => {
    onChange(field, e.target.value);
  };

  return (
    <div className="device-form-card">
      {/* Section Header */}
      <div className="device-form-section-header">
        <div className="device-form-section-num">
          {isEdit ? '✎' : '1'}
        </div>
        <h2 className="device-form-section-title">Device Information</h2>
      </div>

      {/* Form Grid */}
      <div className="device-form-grid">
        {/* Device ID */}
        <div className="device-form-field">
          <label className="device-form-label">Device ID</label>
          <input
            className="device-form-input readonly"
            type="text"
            value={isEdit ? (formData.deviceId || '') : 'Auto generated'}
            readOnly
          />
          <span className="device-form-hint">
            {isEdit ? 'Unique system-generated device ID (read-only)' : 'Automatically generated by the system'}
          </span>
        </div>

        {/* Device Code */}
        <div className="device-form-field">
          <label className="device-form-label">
            Device Code <span className="required-star">*</span>
          </label>
          <input
            className={`device-form-input ${errors.deviceCode ? 'error' : ''}`}
            type="text"
            placeholder="Enter device code"
            value={formData.deviceCode || ''}
            onChange={handleChange('deviceCode')}
          />
          <span className="device-form-hint">Unique code for this device</span>
          {errors.deviceCode && (
            <span className="device-form-error">⚠ {errors.deviceCode}</span>
          )}
        </div>

        {/* Device Name */}
        <div className="device-form-field">
          <label className="device-form-label">
            Device Name <span className="required-star">*</span>
          </label>
          <input
            className={`device-form-input ${errors.deviceName ? 'error' : ''}`}
            type="text"
            placeholder="Enter device name"
            value={formData.deviceName || ''}
            onChange={handleChange('deviceName')}
          />
          <span className="device-form-hint">Descriptive name for the device</span>
          {errors.deviceName && (
            <span className="device-form-error">⚠ {errors.deviceName}</span>
          )}
        </div>

        {/* Device Type */}
        <div className="device-form-field">
          <label className="device-form-label">
            Device Type <span className="required-star">*</span>
          </label>
          <select
            className={`device-form-select ${errors.deviceType ? 'error' : ''}`}
            value={formData.deviceType || ''}
            onChange={handleChange('deviceType')}
          >
            <option value="">Select the type of device</option>
            <option value="Bus Unit">Bus Unit</option>
            <option value="Roadside Unit">Roadside Unit</option>
          </select>
          <span className="device-form-hint">Select the type of device</span>
          {errors.deviceType && (
            <span className="device-form-error">⚠ {errors.deviceType}</span>
          )}
        </div>

        {/* MAC Address */}
        <div className="device-form-field">
          <label className="device-form-label">
            MAC Address {isEdit && <span className="required-star">*</span>}
          </label>
          <input
            className={`device-form-input ${errors.macAddress ? 'error' : ''}`}
            type="text"
            placeholder="Enter MAC address (e.g., 00:1A:2B:3C:4D:5E)"
            value={formData.macAddress || ''}
            onChange={handleChange('macAddress')}
          />
          <span className="device-form-hint">Physical (MAC) address</span>
          {errors.macAddress && (
            <span className="device-form-error">⚠ {errors.macAddress}</span>
          )}
        </div>

        {/* IP Address */}
        <div className="device-form-field">
          <label className="device-form-label">
            IP Address {isEdit && <span className="required-star">*</span>}
          </label>
          <input
            className={`device-form-input ${errors.ipAddress ? 'error' : ''}`}
            type="text"
            placeholder="Enter IP address (e.g., 10.10.1.101)"
            value={formData.ipAddress || ''}
            onChange={handleChange('ipAddress')}
          />
          <span className="device-form-hint">IP address of the device</span>
          {errors.ipAddress && (
            <span className="device-form-error">⚠ {errors.ipAddress}</span>
          )}
        </div>

        {/* Firmware Version */}
        <div className="device-form-field">
          <label className="device-form-label">
            Firmware Version {isEdit && <span className="required-star">*</span>}
          </label>
          <input
            className={`device-form-input ${errors.firmwareVersion ? 'error' : ''}`}
            type="text"
            placeholder="Enter firmware version (e.g., v2.3.4)"
            value={formData.firmwareVersion || ''}
            onChange={handleChange('firmwareVersion')}
          />
          <span className="device-form-hint">Current firmware version</span>
          {errors.firmwareVersion && (
            <span className="device-form-error">⚠ {errors.firmwareVersion}</span>
          )}
        </div>

        {/* Installation Date */}
        <div className="device-form-field">
          <label className="device-form-label">
            Installation Date {isEdit && <span className="required-star">*</span>}
          </label>
          <input
            className={`device-form-input ${errors.installationDate ? 'error' : ''}`}
            type="date"
            value={formData.installationDate || ''}
            onChange={handleChange('installationDate')}
          />
          <span className="device-form-hint">Date when the device was installed</span>
          {errors.installationDate && (
            <span className="device-form-error">⚠ {errors.installationDate}</span>
          )}
        </div>

        {/* Last Seen */}
        <div className="device-form-field">
          <label className="device-form-label">
            Last Seen {isEdit && <span className="required-star">*</span>}
          </label>
          <input
            className="device-form-input"
            type="datetime-local"
            value={formData.lastSeen || ''}
            onChange={handleChange('lastSeen')}
          />
          <span className="device-form-hint">Last time the device was seen online</span>
        </div>

        {/* Is Online */}
        <div className="device-form-field">
          <label className="device-form-label">
            Is Online {isEdit && <span className="required-star">*</span>}
          </label>
          <select
            className="device-form-select"
            value={formData.isOnline || ''}
            onChange={handleChange('isOnline')}
          >
            <option value="">Select online status</option>
            <option value="Online">Online</option>
            <option value="Offline">Offline</option>
          </select>
          <span className="device-form-hint">Current connectivity status</span>
        </div>

        {/* Status */}
        <div className="device-form-field">
          <label className="device-form-label">
            Status <span className="required-star">*</span>
          </label>
          <select
            className={`device-form-select ${errors.status ? 'error' : ''}`}
            value={formData.status || ''}
            onChange={handleChange('status')}
          >
            <option value="">Select status</option>
            <option value="Active">Active</option>
            <option value="Inactive">Inactive</option>
            <option value="Maintenance">Maintenance</option>
          </select>
          <span className="device-form-hint">Operational status of the device</span>
          {errors.status && (
            <span className="device-form-error">⚠ {errors.status}</span>
          )}
        </div>

        {/* Created At */}
        <div className="device-form-field">
          <label className="device-form-label">Created At</label>
          <input
            className="device-form-input readonly"
            type="text"
            value={isEdit ? (formData.createdAt || '') : 'Auto generated on save'}
            readOnly
          />
          <span className="device-form-hint">
            {isEdit ? 'Timestamp when the device was created (read-only)' : 'Timestamp when the device is created'}
          </span>
        </div>
      </div>
    </div>
  );
};

export default DeviceInformationForm;
